#!/bin/bash
# foucld.sh

# This script is meant to be a wrapper around the foucl web application.
# Its role is to control the starting and stopping of the application, passing options to the server

. foucld-usage
. foucld-start
. foucld-stop

case $1 in

        start)
                shift
                foucld-start
                ;;

        stop)
                shift
                foucld-stop
                ;;
                
        restart)
                shift
                foucld-stop
                foucld-start
                ;;
        *)
                echo "Unknown command $1" >&2
                foucld-usage >&2
                exit 1
                ;;
esac

